name: jmade
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.5.2
  - attrs=21.4.0
  - backports=1.0
  - backports.zoneinfo=0.2.1
  - brotlipy=0.7.0
  - ca-certificates=2022.4.26
  - certifi=2022.6.15
  - cffi=1.15.1
  - charset-normalizer=2.1.1
  - click=8.1.3
  - colorama=0.4.6
  - cryptography=38.0.2
  - django=3.2.15
  - django-cors-headers=3.13.0
  - djangorestframework=3.13.1
  - djangorestframework_simplejwt=4.4.0
  - et_xmlfile=1.1.0
  - factory_boy=3.2.1
  - faker=15.1.3
  - idna=3.4
  - iniconfig=1.1.1
  - isort=5.10.1
  - krb5=1.19.2
  - libcxx=12.0.0
  - libedit=3.1.20210910
  - libffi=3.3
  - libpq=12.9
  - libsqlite=3.39.2
  - libzlib=1.2.12
  - mccabe=0.7.0
  - ncurses=6.3
  - openpyxl=3.0.9
  - openssl=1.1.1s
  - packaging=21.3
  - pip=22.1.2
  - pluggy=1.0.0
  - psycopg2=2.8.6
  - py=1.11.0
  - pycodestyle=2.9.1
  - pycparser=2.21
  - pydocstyle=6.1.1
  - pyjwt=1.7.1
  - pyopenssl=22.1.0
  - pyparsing=3.0.4
  - pysocks=1.7.1
  - pytest=7.1.2
  - pytest-django=4.5.2
  - pytest-html=3.1.1
  - pytest-metadata=2.0.2
  - pytest-mock=3.10.0
  - python=3.8.13
  - python-dateutil=2.8.2
  - python-dotenv=0.21.0
  - python_abi=3.8
  - pytz=2022.2.1
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=63.4.1
  - six=1.16.0
  - snowballstemmer=2.2.0
  - sqlite=3.39.2
  - sqlparse=0.4.2
  - tk=8.6.12
  - tomli=1.2.2
  - tqdm=4.64.1
  - typing-extensions=4.3.0
  - typing_extensions=4.3.0
  - tzdata=2022c
  - urllib3=1.26.12
  - webdriver-manager=3.8.4
  - wheel=0.37.1
  - xz=5.2.5
  - zlib=1.2.12
  - pip:
    - async-generator==1.10
    - django-currentuser==0.5.3
    - exceptiongroup==1.0.0rc9
    - h11==0.14.0
    - outcome==1.2.0
    - pyflakes==2.5.0
    - pyhamcrest==2.0.4
    - pylama==8.4.1
    - selenium==4.5.0
    - sniffio==1.3.0
    - sortedcontainers==2.4.0
    - trio==0.22.0
    - trio-websocket==0.9.2
    - wsproto==1.2.0
