name: study-django
channels:
  - conda-forge
  - defaults
dependencies:
  - asgiref=3.6.0
  - backports.zoneinfo=0.2.1
  - bzip2=1.0.8
  - ca-certificates=2023.5.7
  - django=4.2.1
  - isort=5.12.0
  - libffi=3.4.4
  - mccabe=0.7.0
  - ncurses=6.4
  - openssl=1.1.1t
  - pip=23.0.1
  - pycodestyle=2.10.0
  - pydocstyle=6.3.0
  - pyflakes=2.4.0
  - pylama=7.7.1
  - python=3.11.3
  - python_abi=3.11
  - readline=8.2
  - setuptools=66.0.0
  - snowballstemmer=2.2.0
  - sqlite=3.41.2
  - sqlparse=0.4.4
  - tk=8.6.12
  - tomli=2.0.1
  - typing_extensions=4.5.0
  - tzdata=2023c
  - wheel=0.38.4
  - xz=5.4.2
  - zlib=1.2.13
