name: Backend Linters

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    permissions:
      contents: read
    steps:
    - uses: actions:/checkout@v2
