name: Backend Linters

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions:/checkout@v2
